# Generated by Django 5.2.3 on 2025-06-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_certificacao', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=100)),
                ('ano_conclusao', models.IntegerField()),
                ('link_credencial', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-ano_conclusao'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(help_text='Liste responsabilidades em conquistas em tópicos.')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Detalhes sobre o curso')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('linguagem', 'Linguagem de Programação'), ('framework', 'Framework/Biblioteca'), ('banco_de_dados', 'Banco de Dados'), ('ferramenta', 'Ferramenta'), ('metodologia', 'Metodologia'), ('soft_skill', 'Soft Skill')], max_length=50)),
                ('nivel_de_conhecimento', models.CharField(blank=True, help_text='Avançado, Intermediário, Básico', max_length=50)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='InfoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('titulo_profissional', models.CharField(max_length=150)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('resumo_longo', models.TextField()),
                ('resumo_curto', models.CharField(max_length=250)),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('cv_pdf', models.FileField(blank=True, help_text='Faça o upload do seu CV em PDF.', null=True, upload_to='curriculos/')),
            ],
            options={
                'verbose_name': 'Informação Pessoal',
                'verbose_name_plural': 'Informações Pessoais',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Um identificador único para a URL do projeto.', unique=True)),
                ('descricao_curta', models.CharField(max_length=250)),
                ('descricao_longa', models.TextField()),
                ('tecnologias_usadas', models.CharField(max_length=200)),
                ('link_projeto', models.URLField(blank=True, help_text='Link para o projeto online.', null=True)),
                ('link_github', models.URLField(blank=True, help_text='Link para o repositório GitHub', null=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='projetos_imagens/')),
                ('data_criacao', models.DateField()),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
